apiVersion: v1
kind: ConfigMap
metadata:
  name: test-cm
data:
  variable1: valor1

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-literal
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      ports:
        - containerPort: 80
      env:
        - name: ENVIRONMENT_TEST
          valueFrom:
            configMapKeyRef:
              name: test-cm
              key: variable1

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm-file
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config-dir
