apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pv-volume"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
spec:
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: myclaim
  containers:
    - name: pv-container
      image: nginx:1.7.9
      ports:
        - containerPort: 80
      volumeMounts:
        - name: vol
          mountPath: "/usr/share/nginx/html"

---
apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler2
spec:
  volumes:
    - name: vol
      persistentVolumeClaim:
        claimName: myclaim
  containers:
    - name: pv-container
      image: nginx:1.7.9
      ports:
        - containerPort: 80
      volumeMounts:
        - name: vol
          mountPath: "/usr/share/nginx/html"
